<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9O6SJ1M" ignored="0" name="Admin Login Test with Invalid Data" tests="1" failures="1" timestamp="02 Jul 2022 03:59:19 GMT" time="1.591" errors="0">
  <testcase name="checkAdminLogin" time="1.59" classname="orangehrm.testcases.AdminLoginTestwithInvalidData">
    <failure type="java.io.FileNotFoundException" message="C:\Users\RamaKrishna\OneDrive\Desktop\TestData.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\RamaKrishna\OneDrive\Desktop\TestData.xlsx (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at utils.XLUtils.setCellData(XLUtils.java:126)
	at orangehrm.testcases.AdminLoginTestwithInvalidData.checkAdminLogin(AdminLoginTestwithInvalidData.java:35)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- checkAdminLogin -->
</testsuite> <!-- Admin Login Test with Invalid Data -->
